type = "line-corpus"
metadata = [{name = "body", type = "string"},
            {name = "id", type = "uint"},
            {name = "slug", type = "string"},
            {name = "name", type = "string"},
            {name = "image", type = "string"}]
